### ISSUE TITLE
set language to Esperanto

### ISSUE THREAD

**Issue by bensonsmith** [coljac/kindle_eo_eng#3]
I suggest opening the mobi file in calibre and using the "edit metadata" feature to set the language to "Esperanto".  On my Kindle (Paperwhite, I believe -- they all seem to handle dictionaries a bit differently), it was classed as an alternate English dictionary until I did that.

**Comment by coljac** [comment]
Thanks for this issue. I changed the metadata in the input file to be correct, and also introduced inflections in this version. Try the new file and please report any issues.

Version 2: [Esperanto_english.zip](https://github.com/coljac/kindle_eo_eng/files/6566066/Esperanto_english.zip)
